2016-09-22 18:43:49,174 [Thread-8:139995186718464] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-22 18:47:02,144 [Thread-45:139995186718464] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 226, in audit_req
    'request': request
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'htm'
2016-09-22 18:47:08,901 [Thread-46:139995186718464] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 226, in audit_req
    'request': request
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'html'
2016-09-22 18:52:28,648 [Thread-82:139995197208320] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 226, in audit_req
    'request': request
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 591, in autoescape
    nodelist = parser.parse(('endautoescape',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'linebreaksbar'
2016-09-22 18:52:30,339 [Thread-83:139995197208320] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 226, in audit_req
    'request': request
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 591, in autoescape
    nodelist = parser.parse(('endautoescape',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'linebreaksbar'
2016-09-22 18:52:31,539 [Thread-84:139995197208320] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 226, in audit_req
    'request': request
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 591, in autoescape
    nodelist = parser.parse(('endautoescape',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'linebreaksbar'
2016-09-22 18:53:25,320 [Thread-85:139995197208320] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 226, in audit_req
    'request': request
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 591, in autoescape
    nodelist = parser.parse(('endautoescape',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'spacify'
2016-09-22 18:53:26,335 [Thread-86:139995197208320] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 226, in audit_req
    'request': request
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 591, in autoescape
    nodelist = parser.parse(('endautoescape',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 317, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 633, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 429, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'spacify'
2016-09-23 09:23:38,944 [Thread-100:139995197208320] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-23 09:23:39,517 [Thread-101:139995197208320] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon-precomposed.png
2016-09-23 09:23:39,734 [Thread-102:139995197208320] [django.request:170] [base:get_response] [WARNING]- Not Found: /apple-touch-icon.png
2016-09-23 11:09:16,081 [Thread-127:139995197208320] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-23 11:37:47,331 [Thread-241:139995283666688] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 13:10:35,466 [Thread-465:139995186718464] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 13:14:26,470 [Thread-489:139995283666688] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 13:14:32,415 [Thread-490:139995283666688] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 13:14:34,766 [Thread-491:139995283666688] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 13:14:43,222 [Thread-492:139995283666688] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 13:14:45,107 [Thread-493:139995283666688] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 13:15:10,520 [Thread-495:139995283666688] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 14:10:06,933 [Thread-589:139995197208320] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 191, in audit
    'request': request
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 1021, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/smartif.py", line 197, in parse
    retval = self.expression()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/smartif.py", line 207, in expression
    left = t.nud(self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/smartif.py", line 150, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
TemplateSyntaxError: Unexpected end of expression in if tag.
2016-09-23 14:11:31,372 [Thread-594:139995186718464] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 191, in audit
    'request': request
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 1013, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 945, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/smartif.py", line 168, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/smartif.py", line 179, in translate_token
    return self.create_var(token)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/defaulttags.py", line 948, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/base.py", line 639, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '=="True"' from 'paudit.status=="True"'
2016-09-23 14:21:13,158 [Thread-2:139819021883136] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 217, in audit_req
    'status':status
NameError: global name 'status' is not defined
2016-09-23 14:28:22,529 [Thread-58:140392075159296] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 14:28:29,049 [Thread-61:140392075159296] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 14:28:33,150 [Thread-64:140392075159296] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 14:30:31,858 [Thread-71:140392075159296] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 14:39:16,853 [Thread-79:140392046597888] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 14:39:18,393 [Thread-82:140392046597888] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 16:58:59,594 [Thread-133:140392046597888] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-23 16:59:03,854 [Thread-135:140392046597888] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-23 16:59:09,976 [Thread-137:140392046597888] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-23 16:59:22,834 [Thread-139:140392046597888] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-23 16:59:53,867 [Thread-145:140392046597888] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-23 17:00:16,486 [Thread-152:140392046597888] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-23 17:00:19,961 [Thread-154:140392046597888] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-23 17:01:38,611 [Thread-165:140392075159296] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-09-23 17:29:22,144 [Thread-6:140450799286016] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 201, in audit_req
    return HttpResponse('<pre>%s</pre>' % escape(paudit_result))
NameError: global name 'escape' is not defined
2016-09-23 17:30:37,976 [Thread-7:140450799286016] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 201, in audit_req
    return HttpResponse('<pre>%s</pre>' % escape(paudit_result))
NameError: global name 'escape' is not defined
2016-09-23 17:30:43,633 [Thread-12:140450799286016] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 201, in audit_req
    return HttpResponse('<pre>%s</pre>' % escape(paudit_result))
NameError: global name 'escape' is not defined
2016-09-23 18:15:25,666 [Thread-60:140712828184320] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 18:35:01,324 [Thread-34:140219942639360] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 201, in audit_req
    return render_to_response('formset_return.html',{'data':paudit_result})
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: formset_return.html
2016-09-23 18:46:44,586 [Thread-21:140453300295424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 202, in audit_req
    for i in paudit:
TypeError: 'PAudit' object is not iterable
2016-09-23 18:46:49,505 [Thread-22:140453300295424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 202, in audit_req
    for i in paudit:
TypeError: 'PAudit' object is not iterable
2016-09-23 18:46:50,604 [Thread-23:140453300295424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 202, in audit_req
    for i in paudit:
TypeError: 'PAudit' object is not iterable
2016-09-23 18:46:53,930 [Thread-24:140453300295424] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 65, in _login
    return eval(viewfunc)(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 202, in audit_req
    for i in paudit:
TypeError: 'PAudit' object is not iterable
2016-09-23 18:50:22,667 [Thread-12:139647128393472] [django.request:170] [base:get_response] [WARNING]- Not Found: /audit/”
2016-09-23 18:50:44,849 [Thread-17:139647128393472] [django.request:170] [base:get_response] [WARNING]- Not Found: /audit/onClick=”javascript
2016-09-23 18:51:17,568 [Thread-18:139647128393472] [django.request:170] [base:get_response] [WARNING]- Not Found: /audit/onClick=”javascript
2016-09-23 18:58:59,186 [Thread-102:139647154628352] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 19:03:04,265 [Thread-8:139706658735872] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 183, in audit
    for i in paudit:
UnboundLocalError: local variable 'paudit' referenced before assignment
2016-09-23 19:03:58,812 [Thread-11:139682805446400] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /audit/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 75, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/mywrapper.py", line 57, in _login
    return func(request, *args, **kwargs)
  File "/root/djangoproject/djangoproject/views/views.py", line 178, in audit
    return render_to_response('format_retrun.html',{'data':paudit_result})
UnboundLocalError: local variable 'paudit_result' referenced before assignment
2016-09-23 19:18:36,014 [Thread-83:140203734931200] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 19:19:56,493 [Thread-88:140203734931200] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 19:21:16,406 [Thread-93:140203761166080] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 19:22:20,788 [Thread-98:140203734931200] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /getaction/
Traceback (most recent call last):
  File "/server/software/pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    % (callback.__module__, view_name))
ValueError: The view djangoproject.views.views.getaction didn't return an HttpResponse object. It returned None instead.
2016-09-23 19:24:12,913 [Thread-108:140203734931200] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
